- name: List available simulator runtimes
  shell: >
    /usr/local/bin/xcversion simulators |
    grep 'not installed' |
    cut '-d ' -f1,2
  register: available_simulators
  environment:
    GEM_HOME: "{{ system_gem_dir }}"
    GEM_PATH: "{{ system_gem_dir }}"
    XCODE_INSTALL_USER: "{{ xcode_install_user }}"
    XCODE_INSTALL_PASSWORD: "{{ xcode_install_password }}"

- name: Install simulator runtimes
  shell: >
    echo '' | /usr/local/bin/xcversion simulators '--install={{ item }}';
    rm /Users/travis/Library/Caches/XcodeInstall/*.{pkg,dmg}
  loop: "{{ available_simulators.stdout_lines }}"
  environment:
    GEM_HOME: "{{ system_gem_dir }}"
    GEM_PATH: "{{ system_gem_dir }}"
    XCODE_INSTALL_USER: "{{ xcode_install_user }}"
    XCODE_INSTALL_PASSWORD: "{{ xcode_install_password }}"
