- name: Create users
  user:
    name: "{{ item.key }}"
    groups:
    - sudo
    - ssh-user
    shell: /bin/bash
    home: /home/{{ item.key }}
  loop: "{{ users|dict2items }}"
  become: true

- name: Add user keys from GitHub
  authorized_key:
    user: "{{ item.key }}"
    key: https://github.com/{{ item.value }}.keys
    exclusive: true
  loop: "{{ users|dict2items }}"
  become: true
